apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: azure-example-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-store
  target:
    name: azure-example-secret
  data:
    - secretKey: example-secret
      remoteRef:
        key: example-secret
