keys:
  - &peterstorm age1a6sl06c8qhe39d6ss2fvvh37uq74vdakur3dx2f7708u9tlkxf8q4zjk9l
creation_rules:
  # Common secrets - accessible to all hosts/users
  - path_regex: secrets/common/.*\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *peterstorm
  # Host-specific secrets  
  - path_regex: secrets/hosts/.*/.*\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *peterstorm
  # User-specific secrets
  - path_regex: secrets/users/.*/.*\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *peterstorm
  # Legacy: Direct files in secrets/ (for backward compatibility)
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *peterstorm
