keys:
  - &peterstorm age1a6sl06c8qhe39d6ss2fvvh37uq74vdakur3dx2f7708u9tlkxf8q4zjk9l
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *peterstorm
