apiVersion: v1
kind: PersistentVolume
metadata:
  name: "media-ssd"
  labels:
    type: "local"
spec:
  storageClassName: local-path
  capacity:
    storage: "400Gi"
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/data"
