apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: echoserver
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
      - image: ealen/echo-server:0.9.2
        imagePullPolicy: Always
        name: echoserver
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "80"
