apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://kubernetes-sigs.github.io/external-dns
    targetRevision: 1.14.1
    chart: external-dns
    helm:
     valueFiles:
     - $values/k8s/argocd/external-dns/values.yaml
  - repoURL: https://github.com/peterstorm/.dotfiles.git
    targetRevision: HEAD
    ref: values
  - repoURL: https://github.com/peterstorm/.dotfiles.git
    targetRevision: HEAD
    path: k8s/argocd/external-dns/secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
