apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://codecentric.github.io/helm-charts
    targetRevision: 18.4.4
    chart: keycloak
    helm:
     valueFiles:
     - $values/k8s/argocd/keycloak/values.yaml
  - repoURL: https://github.com/peterstorm/.dotfiles.git
    targetRevision: HEAD
    ref: values
  - repoURL: https://github.com/peterstorm/.dotfiles.git
    targetRevision: HEAD
    path: k8s/argocd/keycloak/secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
