apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-plex
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://github.com/peterstorm/.dotfiles.git
    path: /k8s/argocd/kube-plex/charts/
    targetRevision: 0.2.7
    chart: kube-plex
    helm:
     valueFiles:
     - $values/k8s/argocd/kube-plex/values.yaml
  - repoURL: https://github.com/peterstorm/.dotfiles.git
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
