apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: transmission-openvpn
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://bananaspliff.github.io/geek-charts
    targetRevision: 0.1.0
    chart: transmission-openvpn
    helm:
     valueFiles:
     - $values/k8s/argocd/transmission-openvpn/values.yaml
  - repoURL: https://github.com/peterstorm/.dotfiles.git
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
