apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bitnami-postgress-keycloak-password
spec:
  refreshInterval: 0h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-store
  target:
    name: bitnami-postgress-keycloak-password
  data:
    - secretKey: postgress-password
      remoteRef:
        key: bitnami-postgress-keycloak-password

