apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-admin-secret
spec:
  refreshInterval: 0h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-store
  target:
    name: keycloak-admin-secret
  data:
    - secretKey: user
      remoteRef:
        key: keycloak-admin
