ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    external-dns.alpha.kubernetes.io/target: 192.168.0.240
  ingressClassName: nginx
  hostname: keycloak.peterstorm.io
  tls: true
extraEnvVars:
  - name: KEYCLOAK_ADMIN
    valueFrom:
      secretKeyRef:
        name: "keycloak-admin-secret"
        key: "user"
  - name: KEYCLOAK_ADMIN_PASSWORD
    valueFrom:
      secretKeyRef:
        name: "keycloak-password-secret"
        key: "password"
postgres:
  auth:
    existingSecret: "bitnami-postgress-keycloak-password"
