ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    external-dns.alpha.kubernetes.io/target: 192.168.0.240
  ingressClassName: nginx
  tls:
  - hosts:
    - keycloak.peterstorm.io
    secretName: keycloak-peterstorm-tls
  rules:
  - host: keycloak.peterstorm.io
    paths:
    - path: /
      pathType: Prefix

postgresql:
  enabled: true
