apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token-dns
spec:
  refreshInterval: 0h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-store
  target:
    name: cloudflare-api-token-dns
  data:
    - secretKey: cloudflare_api_token
      remoteRef:
        key: cloudflare-api-token-secret
