apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflared-credentials
spec:
  refreshInterval: 0h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-store
  target:
    name: cloudflared-credentials
  data:
    - secretKey: cloudflared-credentials
      remoteRef:
        key: cloudflared-credentials
