apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotslash-dev
  labels:
    app: dotslash-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotslash-dev
  template:
    metadata:
      labels:
        app: dotslash-dev
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: dotslash-dev
          image: ghcr.io/peterstorm/dotslash-dev:sha-45a39b2
          ports:
            - containerPort: 3000
          env:
            - name: HOSTNAME
              value: "0.0.0.0"
          volumeMounts:
            - name: data
              mountPath: /app/data
      volumes:
        - name: data
          emptyDir: {}
